### ISSUE TITLE
running error

### ISSUE THREAD

**Issue by Victoria2333** [varun-suresh/Clustering#3]
Hi Varun,
I test your code,and it appeared:
~/Clustering$ python demo.py --lfw_path ./lfw -v LightenedCNN_A_lfw.mat 
----------------------------------------------------------------------------------------------
Distance calculation time : 52.4087600708
N Clusters: 6854, thresh: 1.1
No of clusters: 6854
Threshold : 1.1
Traceback (most recent call last):
  File "demo.py", line 113, in <module>
    f1_score = evaluate_clusters(clusters['clusters'], labels_lookup)
  File "demo.py", line 64, in evaluate_clusters
    precision, recall = calculate_pairwise_pr(clusters, labels_lookup)
  File "/home/king/Clustering/evaluation.py", line 30, in calculate_pairwise_pr
    cp, tp = count_correct_pairs(cluster, labels_lookup)
  File "/home/king/Clustering/evaluation.py", line 16, in count_correct_pairs
    if labels_lookup[f1] == labels_lookup[f2]:
KeyError: 8944
---------------------------------------------------------------
But when i tried B and C,it is ok,here is the result:
------------------------------------------------------------------------------------------------
~/Clustering$ python demo.py --lfw_path ./lfw -v LightenedCNN_C_lfw.mat 
Distance calculation time : 51.666009903
N Clusters: 6987, thresh: 1.1
No of clusters: 6987
Threshold : 1.1
Correct Pairs that are in the same cluster:196778
Total pairs as per the clusters created: 204500
Total possible true pairs:242225.0
Precision : 0.962239608802
Recall : 0.812376922283
f1_score : 0.880980468969
---------------------------------------------------------

And another question is about the visualization, 
when i tried json.load(),it got:
------------------------------------------------------
  File "visualize.py", line 72, in <module>
    clusters = json.load(args.clusters)
  File "/usr/lib/python2.7/json/__init__.py", line 286, in load
    return loads(fp.read(),
AttributeError: 'str' object has no attribute 'read'
-------------------------------------------------------------
when i tried json.loads(),it got:
--------------------------------------------------------------
  File "visualize.py", line 72, in <module>
    clusters = json.loads(args.clusters)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
------------------------------------------------------------------------
please give me some tips,thank you~~~

**Comment by varun-suresh** [comment]
Hi @Victoria2333 , I have fixed the visualization script. You should now be able to visualize the clusters. I looked at the difference between `lightenedCNN_A_lfw.mat` and `lightenedCNN_C_lfw.mat`. The way they store the `labels_original` is slightly different and hence the failure. For now the code works only for the `lightenedCNN_B_lfw.mat` and `lightenedCNN_C_lfw.mat`. It should be fairly straightforward to get it to work for `lightenedCNN_A_lfw.mat` as well, so if you get it to work, please send in a PR. 

Thanks
