### ISSUE TITLE
how to set the value of n_neighbors and thresh?  when most of face in datasets is isolated, I think your method will be invalid?

### ISSUE THREAD

**Issue by maliho0803** [varun-suresh/Clustering#7]
cluster(vectors, n_neighbors=200, thresh= [1.1])
what is your principle of setting the n_neighbors and thresh?

moreover, when most of face in datasets is isolated, I think your method will be invalid?

**Comment by varun-suresh** [comment]
n_neighbors = 200 is a good place to start. The threshold is a heuristic. If the neural network that generates the vectors for faces is good, it should be able to differentiate between faces. This algorithm is just for clustering. The quality of your results is largely dependent on the vectors it is fed.

**Comment by maliho0803** [comment]
@varun-suresh thank you very much for your reply!
what do you think of my second questions?
In such case, there are two isolated face images, A and B,  in one face datasets. when A is the first order of B, at the same time B is also the first order of A, I think they will always group together, though actually they are different identity!

**Comment by varun-suresh** [comment]
If most faces in a dataset are different, clustering by itself doesn't make much sense. :)
