### ISSUE TITLE
run error 

### ISSUE THREAD

**Issue by albertyou2** [varun-suresh/Clustering#8]
When I cluster.py
I got this error :: 
Traceback (most recent call last):
  File "clustering.py", line 4, in <module>
    import pyflann
  File "/Users/youyin/anaconda3/lib/python3.6/site-packages/pyflann/__init__.py", line 27, in <module>
    from index import *
ModuleNotFoundError: No module named 'index'

My python version is 3.6.4
Do you have any suggestions?Thank you

**Comment by ADAGUGUGUGU** [comment]
pyflann does not have support for python 3 yet, according to this GitHub issue. Your two options are:

Install the pyflann-py3 package:

pip install pyflann-py3
Or, you could take the advice from the issue and use 2to3:

sudo 2to3 -w D:\Anaconda3\lib\site-packages\pyflann


from network is useful
